/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  async redirects() {
    return [
      { source: '/blog/f4-visa-goso-registration-guide-2026', destination: '/blog/f4-visa-goso-registration', permanent: true },
      { source: '/blog/f4-visa-renewal-guide-2026', destination: '/blog/f4-visa-renewal', permanent: true },
      { source: '/blog/f4-visa-eligibility-overseas-koreans-2026', destination: '/blog/f4-visa-eligibility', permanent: true },
      { source: '/blog/f4-visa-eligibility-documents-2026', destination: '/blog/f4-visa-eligibility-documents', permanent: true },
      { source: '/blog/f4-visa-extension-guide-202605', destination: '/blog/f4-visa-extension-guide', permanent: true },
      { source: '/blog/f4-visa-renewal-complete-guide-2026', destination: '/blog/f4-visa-renewal-complete-guide', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-202609', destination: '/blog/f4-to-f5-conversion-guide', permanent: true },
      { source: '/blog/f4-health-insurance-guide-2026-06-03', destination: '/blog/f4-health-insurance-guide', permanent: true },
      { source: '/blog/f4-visa-health-insurance-202605', destination: '/blog/f4-visa-health-insurance', permanent: true },
      { source: '/blog/f4-visa-real-estate-purchase-20260601', destination: '/blog/f4-visa-real-estate-purchase', permanent: true },
      { source: '/blog/f4-visa-required-documents-2026', destination: '/blog/f4-visa-required-documents', permanent: true },
      { source: '/blog/overseas-korean-property-20260530', destination: '/blog/overseas-korean-property', permanent: true },
      { source: '/blog/f4-visa-domestic-renewal-guide-2026-06-02', destination: '/blog/f4-visa-domestic-renewal-guide', permanent: true },
      { source: '/blog/2026-05-24-f4-visa-eligibility', destination: '/blog/f4-visa-eligibility', permanent: true },
      { source: '/blog/dual-nationality-korea-guide-2026', destination: '/blog/dual-nationality-korea-guide', permanent: true },
      { source: '/blog/korean-nationality-recovery-guide-2026', destination: '/blog/korean-nationality-recovery-guide', permanent: true },
      { source: '/blog/korean-nationality-loss-guide-2026', destination: '/blog/korean-nationality-loss-guide', permanent: true },
      { source: '/blog/jaemi-gyopo-f4-visa-application-guide-2026', destination: '/blog/jaemi-gyopo-f4-visa-application-guide', permanent: true },
      { source: '/blog/f4-visa-health-insurance-guide-2026', destination: '/blog/f4-visa-health-insurance-guide', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-202608', destination: '/blog/f4-to-f5-conversion-guide-2', permanent: true },
      { source: '/blog/geo-so-jeung-required-documents-2026', destination: '/blog/geo-so-jeung-required-documents', permanent: true },
      { source: '/blog/f4-sojourn-extension-20260530', destination: '/blog/f4-sojourn-extension', permanent: true },
      { source: '/blog/f4-yureop-ho-gallsin-2026', destination: '/blog/f4-yureop-ho-gallsin', permanent: true },
      { source: '/blog/f4-visa-f5-conversion-20260527', destination: '/blog/f4-visa-f5-conversion', permanent: true },
      { source: '/blog/overseas-korean-real-estate-purchase-procedure-tax-2026', destination: '/blog/overseas-korean-real-estate-purchase-procedure-tax', permanent: true },
      { source: '/blog/jaeil-gyopo-f4-visa-application-guide-2026', destination: '/blog/jaeil-gyopo-f4-visa-application-guide', permanent: true },
      { source: '/blog/f4-to-f5-points-requirement-2026-06-02', destination: '/blog/f4-to-f5-points-requirement', permanent: true },
      { source: '/blog/f4-visa-family-entry-guide-2026', destination: '/blog/f4-visa-family-entry-guide', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-202607', destination: '/blog/f4-to-f5-conversion-guide-3', permanent: true },
      { source: '/blog/nationality-renunciation-korea-2026', destination: '/blog/nationality-renunciation-korea', permanent: true },
      { source: '/blog/f4-visa-eligible-jobs-202605', destination: '/blog/f4-visa-eligible-jobs', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-202606', destination: '/blog/f4-to-f5-conversion-guide-4', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-2026-06-03', destination: '/blog/f4-to-f5-conversion-guide-5', permanent: true },
      { source: '/blog/f4-visa-required-documents-complete-2026', destination: '/blog/f4-visa-required-documents-complete', permanent: true },
      { source: '/blog/f4-visa-renewal-paperwork-immigration-2026', destination: '/blog/f4-visa-renewal-paperwork-immigration', permanent: true },
      { source: '/blog/f4-residence-card-agency-minimum-korea-stay-2026', destination: '/blog/f4-residence-card-agency-minimum-korea-stay', permanent: true },
      { source: '/blog/f4-visa-employment-permitted-jobs-2026-06-04', destination: '/blog/f4-visa-employment-permitted-jobs', permanent: true },
      { source: '/blog/2026-05-24-f4-visa-renewal', destination: '/blog/f4-visa-renewal', permanent: true },
      { source: '/blog/f4-visa-requirements-20260527', destination: '/blog/f4-visa-requirements', permanent: true },
      { source: '/blog/f4-visa-eligible-jobs-202606', destination: '/blog/f4-visa-eligible-jobs-2', permanent: true },
      { source: '/blog/f4-to-f5-conversion-guide-202605', destination: '/blog/f4-to-f5-conversion-guide-6', permanent: true },
      { source: '/blog/f4-visa-extension-guide-202609', destination: '/blog/f4-visa-extension-guide-2', permanent: true },
      { source: '/blog/jemi-dongpo-geo-so-jeung-guide-2026', destination: '/blog/jemi-dongpo-geo-so-jeung-guide', permanent: true },
      { source: '/blog/f4-visa-renewal-2026-documents-procedure-update', destination: '/blog/f4-visa-renewal-documents-procedure-update', permanent: true },
      { source: '/blog/f4-visa-us-pr-documents-202605', destination: '/blog/f4-visa-us-pr-documents', permanent: true },
      { source: '/blog/f4-visa-address-registration-2026-06-04', destination: '/blog/f4-visa-address-registration', permanent: true },
      { source: '/blog/f4-visa-passport-renewal-2026-06-04', destination: '/blog/f4-visa-passport-renewal', permanent: true },
      { source: '/blog/f4-visa-extension-procedure-20260527', destination: '/blog/f4-visa-extension-procedure', permanent: true },
      { source: '/blog/overseas-korean-nationality-recovery-f4-transition-2026', destination: '/blog/overseas-korean-nationality-recovery-f4-transition', permanent: true },
      { source: '/blog/f4-visa-health-insurance-enrollment-2026-06-02', destination: '/blog/f4-visa-health-insurance-enrollment', permanent: true },
      { source: '/blog/geo-so-jeung-guide-2026', destination: '/blog/geo-so-jeung-guide', permanent: true },
      { source: '/blog/f4-visa-health-insurance-guide-20260531', destination: '/blog/f4-visa-health-insurance-guide-2', permanent: true },
      { source: '/blog/f4-to-f5-permanent-residence-20260601', destination: '/blog/f4-to-f5-permanent-residence', permanent: true },
      { source: '/blog/f4-visa-eligible-jobs-202607', destination: '/blog/f4-visa-eligible-jobs-3', permanent: true },
      { source: '/blog/f4-visa-extension-guide-202608', destination: '/blog/f4-visa-extension-guide-3', permanent: true },
      { source: '/blog/f4-visa-employment-activities-guide-20260531', destination: '/blog/f4-visa-employment-activities-guide', permanent: true },
      { source: '/blog/f4-visa-overseas-korean-eligibility-2026', destination: '/blog/f4-visa-overseas-korean-eligibility', permanent: true },
      { source: '/blog/f4-visa-children-school-enrollment-20260601', destination: '/blog/f4-visa-children-school-enrollment', permanent: true },
      { source: '/blog/f4-visa-business-registration-korea-202605', destination: '/blog/f4-visa-business-registration-korea', permanent: true },
      { source: '/blog/f4-bukmi-dongpo-2026', destination: '/blog/f4-bukmi-dongpo', permanent: true },
      { source: '/blog/f4-ilbon-dongpo-2026', destination: '/blog/f4-ilbon-dongpo', permanent: true },
      { source: '/blog/f4-visa-to-f5-permanent-residency-20260531', destination: '/blog/f4-visa-to-f5-permanent-residency-2', permanent: true },
      { source: '/blog/f4-residence-card-application-guide-2026', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/f4-visa-eligibility-check-20260530', destination: '/blog/f4-visa-eligibility-check', permanent: true },
      { source: '/blog/f4-visa-extension-guide-202607', destination: '/blog/f4-visa-extension-guide-4', permanent: true },
      { source: '/blog/f4-visa-eligible-jobs-202608', destination: '/blog/f4-visa-eligible-jobs-4', permanent: true },
      { source: '/blog/f4-visa-renewal-documents-procedure-2026-latest', destination: '/blog/f4-visa-renewal-documents-procedure-latest', permanent: true },
      { source: '/blog/f4-visa-real-estate-purchase-2026-06-03', destination: '/blog/f4-visa-real-estate-purchase-2', permanent: true },
      { source: '/blog/f4-visa-extension-guide-202606', destination: '/blog/f4-visa-extension-guide-5', permanent: true },
      { source: '/blog/f4-visa-eligible-jobs-202609', destination: '/blog/f4-visa-eligible-jobs-5', permanent: true },
      { source: '/blog/f4-visa-real-estate-purchase-guide-2026', destination: '/blog/f4-visa-real-estate-purchase-guide', permanent: true },
      { source: '/blog/2026-05-24-f4-visa-goso-registration', destination: '/blog/f4-visa-goso-registration', permanent: true },
      { source: '/blog/f4-visa-renewal-procedure-2026', destination: '/blog/f4-visa-renewal-procedure-2', permanent: true },
      // Duplicate content 301 redirects
      { source: '/blog/f4-domestic-residence-report-procedure', destination: '/blog/f4-domestic-residence-filing-steps', permanent: true },
      { source: '/blog/f4-domestic-residence-registration', destination: '/blog/f4-domestic-residence-filing-steps', permanent: true },
      { source: '/blog/f4-domestic-residence-report', destination: '/blog/f4-domestic-residence-filing-steps', permanent: true },
      { source: '/blog/f4-residence-report-guide', destination: '/blog/f4-domestic-residence-filing-steps', permanent: true },
      { source: '/blog/overseas-korean-domestic-residence-report', destination: '/blog/f4-domestic-residence-filing-steps', permanent: true },
      { source: '/blog/f4-residence-card-issuance-documents-timeline', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/f4-residence-card-issuance', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/f4-residence-card-reissue-lost-damaged', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/f4-residence-card-reissue', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/residence-card-guide', destination: '/blog/f4-residence-card-application-guide', permanent: true },
      { source: '/blog/f4-visa-applicant-eligibility-korean-heritage-scope', destination: '/blog/f4-eligibility-overseas-korean-scope', permanent: true },
      { source: '/blog/f4-visa-eligibility-scope', destination: '/blog/f4-eligibility-overseas-korean-scope', permanent: true },
      { source: '/blog/f4-visa-eligibility-check-guide', destination: '/blog/f4-eligibility-overseas-korean-scope', permanent: true },
      { source: '/blog/f4-visa-eligibility-documents-2026', destination: '/blog/f4-eligibility-overseas-korean-scope', permanent: true },
      { source: '/blog/f4-visa-employment-field-summary', destination: '/blog/f4-visa-allowed-jobs-restricted-industries', permanent: true },
      { source: '/blog/f4-visa-employment-occupations', destination: '/blog/f4-visa-allowed-jobs-restricted-industries', permanent: true },
      { source: '/blog/f4-male-age-25-military-rule', destination: '/blog/f4-visa-military-service', permanent: true },
      { source: '/blog/f4-visa-military-service-note', destination: '/blog/f4-visa-military-service', permanent: true },
      { source: '/blog/f4-visa-military-service-unfulfilled-restriction', destination: '/blog/f4-visa-military-service', permanent: true },
      { source: '/blog/f4-visa-extension-deadline-compliance', destination: '/blog/f4-visa-renewal-procedure', permanent: true },
      { source: '/blog/f4-visa-renewal-cycle-documents', destination: '/blog/f4-visa-renewal-procedure', permanent: true },
      { source: '/blog/f4-visa-renewal-procedure-2026', destination: '/blog/f4-visa-renewal-procedure', permanent: true },
      { source: '/blog/f4-visa-renewal-procedure-guide', destination: '/blog/f4-visa-renewal-procedure', permanent: true },
      { source: '/blog/f4-visa-business-registration-guide', destination: '/blog/f4-visa-business-registration', permanent: true },
      { source: '/blog/f4-visa-chinese-korean-eligibility-restrictions', destination: '/blog/f4-visa-chinese-koreans', permanent: true },
      { source: '/blog/f4-visa-us-citizen-application-procedure', destination: '/blog/f4-visa-us-citizens', permanent: true },
      { source: '/blog/us-citizenship-korea-nationality-auto-loss', destination: '/blog/f4-visa-us-citizens', permanent: true },
      { source: '/blog/us-citizenship-korean-nationality-loss-guide', destination: '/blog/f4-visa-us-citizens', permanent: true },
      { source: '/blog/nationality-recovery-application', destination: '/blog/nationality-recovery', permanent: true },
      { source: '/blog/nationality-recovery-minors', destination: '/blog/nationality-recovery', permanent: true },
      { source: '/blog/nationality-recovery-review', destination: '/blog/nationality-recovery', permanent: true },
      { source: '/blog/overseas-korean-nationality-recovery-procedure', destination: '/blog/nationality-recovery', permanent: true },
      { source: '/blog/f4-residence-address-change', destination: '/blog/f4-address-change-notification', permanent: true },
      { source: '/blog/f4-visa-to-f5-permanent-residency', destination: '/blog/f4-to-f5-permanent-residency-conversion', permanent: true },
    ]
  },
}

export default nextConfig
